### ISSUE TITLE
add GitHub action workflow to create release

### ISSUE THREAD

**Issue by sehz** [infinyon/future-aio#36]

**Comment by yzwdroid** [comment]
can I try this?

**Comment by sehz** [comment]
Yes, that would be appreciated

**Comment by yzwdroid** [comment]
Hi @sehz, I have two questions about this:  
- To trigger the release, how about everytime we push to the master branch with a tag starting with V like v0.10.1
- What do we need to upload besides the source code.

**Comment by sehz** [comment]
Besides source code, change list should be added to release.  We don't have change list but we can start create one
