### ISSUE TITLE
Timer feature does not enable futures-lite

### ISSUE THREAD

**Issue by nickbabcock** [infinyon/future-aio#40]
On a blank node-bindgen repo I ran `nj-cli build` and the build failed with:

```
error[E0433]: failed to resolve: use of undeclared type or module `futures_lite`
  --> /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/fluvio-future-0.1.10/src/timer.rs:10:9
   |
10 |     use futures_lite::future::Future;
   |         ^^^^^^^^^^^^ use of undeclared type or module `futures_lite`
```

[Looks like the timer feature needs `futures_lite`](https://github.com/infinyon/future-aio/blob/2cbdc110d8d65f41b206b0b7c716e7ad5e647b5e/src/timer.rs#L10) but [does not enable it](https://github.com/infinyon/future-aio/blob/2cbdc110d8d65f41b206b0b7c716e7ad5e647b5e/Cargo.toml#L20).

**Comment by sehz** [comment]
thanks for reporting this. let me check

**Comment by sehz** [comment]
fixed.  perform `cargo update`
